CXX      ?= g++
CXXFLAGS ?= -std=c++20
CPPFLAGS ?= -O3 -Wall -pedantic -I.  
LDFLAGS ?= 
LDLIBS  ?= 
LINK.o := $(LINK.cc) # Use C++ linker.

EXEC = main
SRCS = $(wildcard *.cpp)
OBJS = $(SRCS:.cpp=.o)

.PHONY = all $(EXEC) $(OBJS) clean distclean

.DEFAULT_GOAL = all

all: $(EXEC) 

$(EXEC): $(OBJS) 
	
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) $(OBJS) -o $(EXEC) 

$(OBJS): %.o: %.cpp
	$(CXX) -c $(CPPFLAGS) $(CXXFLAGS) $(SRCS)


clean:
	$(RM) *.o result.txt 

distclean: clean
	$(RM) *~
	$(RM) $(EXEC)